services:
  - type: web
    name: expense-tracker-backend
    env: node
    rootDir: Backend
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
    plan: free
