services:
  - type: web
    name: expense-tracker-backend
    env: node
    rootDir: Backend
    buildCommand: bash ./verify-build.sh
    startCommand: bash ./startup.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
    disk:
      name: backend-disk
      size: 2GB
    plan: free
